from pydantic import Field, BaseModel
from typing import Annotated, List, TypedDict, Literal
from operator import add


class AgentSchema(TypedDict):
    messages: Annotated[list, add] = Field(description="list of messages to be processed by the agent")
    user_question: str
    curated_ques: str = Field(description="the user's question refined by LLM")
    prompt_query: str  = Field(description="a detailed prompt with SQL DB Context that will help agent to generate SQL Query")
    is_safe: Literal["Yes", "No"] = Field(description="if the generated SQL Query is safe to hit the main database")
    generated_sql_query: str = Field(description="the sql query generated by the agent for SQL Query")
    comments: str = Field(description="comments from the is_safe node")
    sql_execution_result: str = Field(description="the result obtained post sql query")
    final_answer: str = Field(description="final answer generated by the llm")

class JudgeSchema(BaseModel):
    answer: Literal["Yes", "No"] = Field(description="if the generated SQL Query is safe to hit the main database")
    comment: str = Field(description="reason for the judgement")